### ISSUE TITLE
Fails with perls < 5.20

### ISSUE THREAD

**Issue by andk** [yanick/perl-json-schema-shorthand#1]
"Need perl 5.20.0 or later for feature postderef" is the diagnostics during test:

http://www.cpantesters.org/cpan/report/acf661b2-7ad1-11e6-bca8-ef00eb7e2f12

I'd suggest to declare the requirement on the tin. That way the FAILS are converted to UNKNOWNS and the enduser gets the message before even trying to run the tests. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes 

Thanks&&Best

**Comment by yanick** [comment]
Good one. Fix is on its way to CPAN. Thanks!
